# 欧式几何相关术语 {-}

在欧几里得的语言中，技术性的术语相对较少。但是也确实有，并且欧几里得并不经常提供如同现代读者所期待的解释。古代的注释者，在他们关于欧几里得的专题论文中也介绍了更多的正式术语。这些及更多术语，曾经是Heath写给他自己3册欧几里得书的一篇介绍性论文的主题。以下材料中的部分内容也取自Heath, 反之他也广泛地从Proclus(公元410-485)及其他注释者进行了引用。

## 原本(Elements) {-}

Proclus说，在整个几何学中，一部分具有领导地位的定理，奠定了其它遵循原理，十分普遍且有衍生出许多特性的证明。这样的定理被称为原本（Elements），并且他们的功用或可以同字母表中的字母与语言的关系相比，在希腊语中，字母也确实被以相同名称定名.

**宣棋随记**
Element在这里是表示某完整的核心部分，感觉中文中的“原本”并没有表达出“部分”这个含义，但是因为《几何原本》这个翻译已沿用多年，为了避免混淆，还是取用原本。

## 对命题的形式性划分 {-}
在古希腊数学中的每一个完整的问题以及定理都包含有以下元素。  

*   声明：陈述已知和所求（或者是做什么或者是证明什么）

*   设置：以字母和实际的点线的方式重复陈述声明中的已知

*   定义或详述：具体通过点和线的方式分别陈述所求

*   构建：用额外的线的方式添加其它

*   证明：从给定事实推理到所需论断

*   结论：重提声明以确认早先提出的内容已经被证明。  

**宣棋随记**  

已知就是给定条件，所求中的"做什么"对应的是下文提及的术语QEF，而证明什么则是对应"QED"。

这个形式性划分的解释十分重要。敲黑板。它十分清楚的显现了从普遍到具体再回到普遍的过程。声明是对命题纯文字的一个概述，设置和定义/详述则是从几何的角度，用具体的点线面图形来具象文字。其中设置对应的是已知（给定条件）；而定义或详述对应的是所求。构建则是在具体中从条件出发到求解中点过程中搭建的桥，特别是需要在图形里具象的部分。证明也是桥，但是是逻辑部分。证明是具体事件的终点。最终，结论是重复声明，但是此时声明已经不是声明，同样的内容已经可以称为既定事实了。也是在这一步，从具体的几何又回到了普遍的声明。

## “综上所述…”(Therefore, etc.) {-}

读者们会发现大部分的命题都会以“综上所述，以上已论证”的方式结尾。下一条会解释“以上已论证”（Q.E.D.）的含义。词语“综上所述”代表对声明的确切的复述。这个复述对于一个完整的论证，在形式上被认为是必需的，因为证明本身经常是以特殊的线和圆为基础，所以必须要做普遍地复述。  

尽管最终的结论被陈述在手写的希腊语文本的手稿中，但是在拉丁语的翻译和返工的实践中，很常见的是全部删除结论部分（比如说1482年的第一版），或者指明通过缩写它的存在（比如说Clavius的1574年返工）。在更仔细的版本中，比如说Commandino的1572年的翻译，会保留完整的结论。  

Heath在他的翻译中遵循了缩写结论的做法。我们没有改变Heath的缩写，但是我们必须强调这里曾有欧几里得十分明显的用意，在命题中完整地陈述结论。也因此，Heath所写的做法（综上所述…）必须被视为等同于完整的陈述。

## “已经论证和已成事实”(Q.E.D. and Q.E.F.) {-}

Q.E.D.在拉丁语中说的是“quod erat demonstradum”（已经论证），就是说已经论证了，是取自古希腊语短语的“o{per e[dei dei`xai ”。但是，这与古希腊语表达的含义略有区别，一个更好的翻译是，“确实被要求的已被证明”。 Q.E.D传统上被置于证明的结尾，这时声明中的指定部分，还有设置，会在论证的结论中被一字不差地重述。（读上文以获得在命题形式性划分中关于传统名称的解释）

Q.E.F.是指”quod erat faciendum”（已成事实），就是说已经被完成了，是取自古希腊语短语“o{per e[dei poih`sai”. 还是一样，这个翻译并不精确。“确实被要求的已被完成”更接近于古希腊语原义。Q.E.F.被置于构建作为结尾的命题。

## 推论 {-#porism}

术语推论指的是在首要命题的证明过程中被揭示的另外一个定理。它是一个推及的，附带的结果。

## 柏拉图的分割线 {-#plato}

在《理想国》的第六卷，柏拉图解释了可见的事物与用几何比喻来理解的事物之间的区别。他写到：

>“现在画一条线段并将之切成不等的两部分，并且依据相同的比例再次进行分割，且我们假定两个对应第一次分割后的主要部分，一个是对应可看见的部分，另一个是对应可理解的部分，就他们的清楚程度和对清楚程度的渴望而言，对比第二次细分出来的四个部分。”

在分割出来的四个部分中，线段最低层次的部分就如同可被看见的图像，第二部分则如同可被看到的事物自身。两个高层次的部分，最上端对应纯粹概念的领域，其下面则是这些概念的图像。关于这些部分之间的关系，柏拉图写道：

> “你可能会意识到，几何、代数、同类相关科学的学生在许多科学的分支研究中，假定奇数和偶数，假定图像还有三种类型的角，假定其它相似的知识。但这些假定是他们猜测每个人都应该知道的知识，所以他们并没有屈尊去描述这些知识，无论是对他们自己还是对其他人。但是在这样一个知识易变得情境下，他们却从这些知识开始研究，并直到最后形成他们的结论。……而且你知道么：当他们使用这些与这些知识相关、可被看到的范式和推理，他们并没有在想这些知识，而是在想与这些知识相像的完美概念；他们并没有在想他们画的图像，而是在想图像中绝对的正方形和绝对的直径；诸如此类。”  

在你学习第一卷的证明时，记住欧几里得的几何学是在柏拉图学院中出现的。柏拉图对于数学范式的这个理想境界，你觉得令人信服么？如果你觉得令人信服，为什么呢？是怎样让人信服的呢？如果你觉得并不令人信服，你更倾向于哪一种可替代的观点？ 

在个别命题建议讨论的话题时，我们将会偶尔的提及这一段分割线的的内容。 

**宣棋随记**

私以为这些问题以及柏拉图的讨论都最终会指向一个问题，数学的存在究竟是什么？数学是不夹杂任何人为干预，对自然纯粹的映射么？还是人类面对自然在思考中创造出来的符号和架构？还是存在于自然与人之中作为联系的纽带？  

至今都记得大一时，老师提供的论文话题清单中有一问：数学是自然还是艺术？我并不能够告诉你这些问题的答案是什么，但是我知道，如果你问自己这些问题，并且思考它，你的答案将反映出你对世界的理解，这些理解可能是你之前从未注意到的。不妨花些时间想一下。另外关于定义是什么、定义如何在整个逻辑架构中起作用的问题，都会帮助我们理解数学“被创造”或者“被发现”的过程。（当你认为数学“被创造”的时候，数学对你来说是人为的智慧结晶，当你选择“被发现”的时候，数学在你的潜意识里是作为自然一部分的存在，你选择了哪一个？）定义作为一个逻辑架构的基石，值得我们仔细考察。
